### ISSUE TITLE
Error when importing a json model

### ISSUE THREAD

**Issue by mainrs** [phonon/blender-minecraft-json#4]
![image](https://user-images.githubusercontent.com/5113257/102397722-90d37980-3fde-11eb-9ba4-a14439240334.png)

**Comment by mainrs** [comment]
I've downloaded Blender 2.83 (LTS) it it works there without throwing an error. So it's probably an incompatibility between the plugin and the newer versions of Blender.

**Comment by Gigabars** [comment]
Very odd, I'm using 2.83 LTS and I get the same error.

**Comment by mainrs** [comment]
> Very odd, I'm using 2.83 LTS and I get the same error.

Me too now. The first time it worked but I tried it yesterday again and got the error on LTS as well.

**Comment by phonon** [comment]
does the .json file youre importing contain elements?

**Comment by mainrs** [comment]
Mine had, I tried the `beacon.json` block model file from 1.16.4.

**Comment by phonon** [comment]
Unable to reproduce, I was able to import beacon.json on both blender 2.83 and 2.91 (beacon.json block model extracted from 1.16.4 minecraft jar).

**Comment by mainrs** [comment]
Maybe I am doing something wrong. Do you import it using File > Import > json model?

Not sure if it is important, but I so had McPrep installrd

**Comment by mainrs** [comment]
@phonon does the plugin follow the parent hierarchy? For example I tried `acacia_log` but that failed. Looking at the json file:
```json
{
  "parent": "minecraft:block/cube_column",
  "textures": {
    "end": "minecraft:block/acacia_log_top",
    "side": "minecraft:block/acacia_log"
  }
}
```
The file doesn't have elements specified. Is there a way to import these kind of files anyway? Maybe by specifying a root directory that the plugin can use (`assets/minecraft/models`) to resolve these files?

**Comment by zNightlord** [comment]
The addon finds the "elements" data in order to work if the json file doesn't content any the error will popup.
To solve this problem to have to find the json file block/cube_column and import it.

I just made something similiar. It finds the parent file in the same directory *found it it will import* but if can't find it, display an error.
There is a problem. I used other json file like this `"parent": "block/cube_column"` don't have the `minecraft:` It works. so I modify a little bit to get rid the `minecraft:` part... but I can't figure out to it work properly.

**Comment by lynrayy** [comment]
Same problem on 2.90.1 and 2.83 LTS
[Screenshot](https://imgur.com/tASEQDw)

**Comment by phonon** [comment]
I updated the importer to trace the parent hierarchy and combine the json data, e.g. for an anvil the .json hierarchy is [anvil.json, template_anvil.json, block.json], the importer will import each of those json files, then merge in reverse order block.json => template_anvil.json => anvil.json. This assumes these files exist and the directory structure is the same as the default Minecraft resource pack. This will also strip out any namespacing in the path references, e.g. "minecraft:block/template_anvil" is just treated as "block/template_anvil", since it's not feasible to manage namespaces in the importer.

I've tested on a few random vanilla block json models and the importer seems to work ok.
